# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    CR32\UserBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_EDITEUR
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers: 
    in_memory:
      memory:
        users:
          user:  { password: userpass, roles: [ 'ROLE_USER' ] }
          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    main:
      entity:
        class: CR32\UserBundle\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:   ^/
      anonymous: true
      provider: main
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path: logout
        target: login

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
