<?php

namespace CR32\QuestionnaireBundle\Repository;

/**
 * DansesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DansesRepository extends \Doctrine\ORM\EntityRepository
{
}
