#Partie QUestionnaire
cr32_questionnaire_home:
    path:     /
    defaults: { _controller: CR32QuestionnaireBundle:Questionnaire:index }

cr32_questionnaire_subscription:
    path:     /abonnement
    defaults: { _controller: CR32QuestionnaireBundle:Questionnaire:subscription }

cr32_questionnaire_thanks:
    path:     /merci
    defaults: { _controller: CR32QuestionnaireBundle:Questionnaire:thanks }

#Partie Administration
cr32_administration_admin:
    path:   /admin
    defaults: { _controller: CR32QuestionnaireBundle:Administration:admin }

cr32_administration_danses:
    path:   /admin/danses/{niveau}
    defaults: 
        _controller: CR32QuestionnaireBundle:Administration:danses 
        niveau: all

cr32_administration_contacts:
    path:   /admin/contacts/{id}
    defaults: 
        _controller: CR32QuestionnaireBundle:Administration:contacts
        id: null

# modification d'une danse
cr32_administration_danse_edit:
    path:   /admin/danse/edit/{id}{niveau}
    defaults: { _controller: CR32QuestionnaireBundle:Administration:editDanse }

# supression d'une danse
cr32_administration_danse_delete:
    path:   /admin/danse/delete/{id}{niveau}
    defaults: { _controller: CR32QuestionnaireBundle:Administration:deleteDanse }