#Partie QUestionnaire
cr32_questionnaire_home:
    path:     /
    defaults: { _controller: CR32QuestionnaireBundle:Questionnaire:index }

cr32_questionnaire_subscription:
    path:     /abonnement
    defaults: { _controller: CR32QuestionnaireBundle:Questionnaire:subscription }

cr32_questionnaire_thanks:
    path:     /merci
    defaults: { _controller: CR32QuestionnaireBundle:Questionnaire:thanks }

#Partie Administration
cr32_administration_admin:
    path:   /admin
    defaults: { _controller: CR32QuestionnaireBundle:Administration:admin }

cr32_administration_danses:
    path:   /admin/danses
    defaults: { _controller: CR32QuestionnaireBundle:Administration:danses }

cr32_administration_contacts:
    path:   /admin/contacts
    defaults: { _controller: CR32QuestionnaireBundle:Administration:contacts }

# supression d'une danse
cr32_administration_danse_delete:
    path:   /admin/danse/delete/{id}
    defaults: { _controller: CR32QuestionnaireBundle:Administration:deleteDanse }

# modification d'une danse
cr32_administration_danse_edit:
    path:   /admin/danse/edit/{id}
    defaults: { _controller: CR32QuestionnaireBundle:Administration:editDanse }

# suppression d'un contact
cr32_administration_contact_delete:
    path:   /admin/contact/delete/{id}
    defaults: { _controller: CR32QuestionnaireBundle:Administration:deleteContact }